In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('../Data/products_4.csv')

In [2]:
df_rj = df[df['Proj_State'] == 'RJ']
df_rj.drop(columns=['Prod_Desc', 'Sub_Name', 'ID_Proj', 'Proj_Name', 'Proj_City'], inplace=True)
df_rj.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_35436\3942908168.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rj.drop(columns=['Prod_Desc', 'Sub_Name', 'ID_Proj', 'Proj_Name', 'Proj_City'], inplace=True)

          Cat_Name  BOM_Quant Proj_State   Proj_Date
20        Madeiras      500.0         RJ  2023-09-06
22        Madeiras      500.0         RJ  2023-09-06
52  Infraestrutura       16.0         RJ  2023-09-20
53  Infraestrutura       16.0         RJ  2023-09-20
68  Infraestrutura       15.0         RJ  2023-09-22

In [ ]:
df_rj.isnull().sum()

In [ ]:
# verificando a quantidade de linhas em Bom_Quant sáo zeros
df_rj[df_rj['BOM_Quant'] == 0]

### Criando um dataset para cada categoria que sera modelada

In [3]:
df_rj_ferragens = df_rj[df_rj['Cat_Name'] == 'Ferragens']
df_rj_construcao_civil = df_rj[df_rj['Cat_Name'] == 'Construção Civil']
df_rj_materiais_eletricos = df_rj[df_rj['Cat_Name'] == 'Materiais Elétricos']

### Agrupamento e Soma de BOM_Quant por Data

In [4]:
df_rj_ferragens_grouped = df_rj_ferragens.groupby('Proj_Date').agg({'BOM_Quant': 'sum'}).reset_index()
df_rj_construcao_civil_grouped = df_rj_construcao_civil.groupby('Proj_Date').agg({'BOM_Quant': 'sum'}).reset_index()
df_rj_materiais_eletricos_grouped = df_rj_materiais_eletricos.groupby('Proj_Date').agg({'BOM_Quant': 'sum'}).reset_index()

In [ ]:
n_duplicates = df_rj_ferragens_grouped.duplicated().sum()
print(f'Número de duplicados: {n_duplicates}')

n_duplicates = df_rj_construcao_civil_grouped.duplicated().sum()
print(f'Número de duplicados: {n_duplicates}')

n_duplicates = df_rj_materiais_eletricos_grouped.duplicated().sum()
print(f'Número de duplicados: {n_duplicates}')

In [ ]:
# Verificando se há valores zero ou negativos
print(df_rj_ferragens_grouped[df_rj_ferragens_grouped['BOM_Quant'] <= 0].shape[0])
print(df_rj_construcao_civil_grouped[df_rj_construcao_civil_grouped['BOM_Quant'] <= 0].shape[0])
print(df_rj_materiais_eletricos_grouped[df_rj_materiais_eletricos_grouped['BOM_Quant'] <= 0].shape[0])

In [ ]:
df_rj_ferragens_grouped.to_csv('../Data/PreparedData/RJ/RJ_FERRAGENS.csv', index=False)
df_rj_construcao_civil_grouped.to_csv('../Data/PreparedData/RJ/RJ_CONSTRUCAO_CIVIL.csv', index=False)
df_rj_materiais_eletricos_grouped.to_csv('../Data/PreparedData/RJ/RJ_MATERIAIS_ELETRICOS.csv', index=False)

In [ ]:
plt.figure(figsize=(12, 6))
df_rj.groupby('Proj_Date').size().plot()
plt.title('Products Over Time')
plt.xlabel('Date')
plt.ylabel('Count')
plt.show()

### Criando datasets semanais

In [5]:
def remove_outliers(df, column):  
    Q1 = df[column].quantile(0.25)  
    Q3 = df[column].quantile(0.75)  
    IQR = Q3 - Q1  
    lower_bound = Q1 - 1.5 * IQR  
    upper_bound = Q3 + 1.5 * IQR  
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

In [6]:
df_rj_ferragens_grouped['Proj_Date'] = pd.to_datetime(df_rj_ferragens_grouped['Proj_Date'])  
df_rj_construcao_civil_grouped['Proj_Date'] = pd.to_datetime(df_rj_construcao_civil_grouped['Proj_Date'])  
df_rj_materiais_eletricos_grouped['Proj_Date'] = pd.to_datetime(df_rj_materiais_eletricos_grouped['Proj_Date'])  
  
df_rj_ferragens_grouped.set_index('Proj_Date', inplace=True)  
df_rj_construcao_civil_grouped.set_index('Proj_Date', inplace=True)  
df_rj_materiais_eletricos_grouped.set_index('Proj_Date', inplace=True)

In [7]:
df_rj_ferragens_semanal = df_rj_ferragens_grouped.resample('W').sum().reset_index()  
df_rj_construcao_civil_semanal = df_rj_construcao_civil_grouped.resample('W').sum().reset_index()  
df_rj_materiais_eletricos_semanal = df_rj_materiais_eletricos_grouped.resample('W').sum().reset_index()

In [9]:
# Substituir zeros por NaN antes da interpolação  
df_rj_ferragens_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)  
df_rj_construcao_civil_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)  
df_rj_materiais_eletricos_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)

In [10]:
df_rj_ferragens_semanal['BOM_Quant'] = df_rj_ferragens_semanal['BOM_Quant'].interpolate(method='linear')  
df_rj_construcao_civil_semanal['BOM_Quant'] = df_rj_construcao_civil_semanal['BOM_Quant'].interpolate(method='linear')  
df_rj_materiais_eletricos_semanal['BOM_Quant'] = df_rj_materiais_eletricos_semanal['BOM_Quant'].interpolate(method='linear')

C:\Users\HP\AppData\Local\Temp\ipykernel_35436\1985175908.py:1: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rj_ferragens_semanal['BOM_Quant'] = df_rj_ferragens_semanal['BOM_Quant'].interpolate(method='linear')
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\1985175908.py:2: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rj_construcao_civil_semanal['BOM_Quant'] = df_rj_construcao_civil_semanal['BOM_Quant'].interpolate(method='linear')
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\1985175908.py:3: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rj_materiais_eletricos_semanal['BOM_Quant'] = df_rj_materiais_eletricos_semanal['BOM_Quant'].interpolate(method='linear')

In [11]:
df_rj_ferragens_no_outliers = remove_outliers(df_rj_ferragens_semanal, 'BOM_Quant')  
df_rj_construcao_civil_no_outliers = remove_outliers(df_rj_construcao_civil_semanal, 'BOM_Quant')  
df_rj_materiais_eletricos_no_outliers = remove_outliers(df_rj_materiais_eletricos_semanal, 'BOM_Quant')

## Verificando se há as series possuem todas as semanas

In [13]:
# Função para calcular a média móvel de 3 valores  
def rolling_mean_imputation(series):  
    result = series.copy()  
    for i in range(len(series)):  
        if pd.isna(series[i]):  
            window = series[max(i-3, 0):i]  
            valid_values = window[~pd.isna(window)]  
            if len(valid_values) > 0:  
                result[i] = valid_values.mean()  
    return result

In [14]:
df_rj_ferragens_no_outliers['Proj_Date'] = pd.to_datetime(df_rj_ferragens_no_outliers['Proj_Date'])  
df_rj_construcao_civil_no_outliers['Proj_Date'] = pd.to_datetime(df_rj_construcao_civil_no_outliers['Proj_Date'])  
df_rj_materiais_eletricos_no_outliers['Proj_Date'] = pd.to_datetime(df_rj_materiais_eletricos_no_outliers['Proj_Date'])  

df_rj_ferragens_no_outliers.set_index('Proj_Date', inplace=True) 
df_rj_construcao_civil_no_outliers.set_index('Proj_Date', inplace=True) 
df_rj_materiais_eletricos_no_outliers.set_index('Proj_Date', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_35436\3511663781.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rj_ferragens_no_outliers['Proj_Date'] = pd.to_datetime(df_rj_ferragens_no_outliers['Proj_Date'])
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\3511663781.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rj_construcao_civil_no_outliers['Proj_Date'] = pd.to_datetime(df_rj_construcao_civil_no_outliers['Proj_Date'])
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\3511663781.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rj_materiais_eletricos_no_outliers['Proj_Date'] = pd.to_datetime(df_rj_materiais_eletricos_no_outliers['Proj_Date'])

In [17]:
# Criar um índice de datas completo com frequência semanal  
full_index_ferragens = pd.date_range(start=df_rj_ferragens_no_outliers.index.min(), end=df_rj_ferragens_no_outliers.index.max(), freq='W')
df_rj_ferragens_no_outliers = df_rj_ferragens_no_outliers.reindex(full_index_ferragens)

full_index_construcao = pd.date_range(start=df_rj_construcao_civil_no_outliers.index.min(), end=df_rj_construcao_civil_no_outliers.index.max(), freq='W')
df_rj_construcao_civil_no_outliers = df_rj_construcao_civil_no_outliers.reindex(full_index_construcao)

full_index_eletrico = pd.date_range(start=df_rj_materiais_eletricos_no_outliers.index.min(), end=df_rj_materiais_eletricos_no_outliers.index.max(), freq='W')
df_rj_materiais_eletricos_no_outliers = df_rj_materiais_eletricos_no_outliers.reindex(full_index_eletrico)

In [24]:
# Repetido até que todos os valores NA sejam preenchidos
df_rj_ferragens_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rj_ferragens_no_outliers['BOM_Quant'])
df_rj_construcao_civil_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rj_construcao_civil_no_outliers['BOM_Quant']) 
df_rj_materiais_eletricos_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rj_materiais_eletricos_no_outliers['BOM_Quant'])

C:\Users\HP\AppData\Local\Temp\ipykernel_35436\3055885078.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(series[i]):
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\3055885078.py:9: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  result[i] = valid_values.mean()

In [25]:
# Verificando se há valores zero ou negativos
print(df_rj_ferragens_no_outliers[df_rj_ferragens_no_outliers['BOM_Quant'] <= 0].shape[0])
print(df_rj_construcao_civil_no_outliers[df_rj_construcao_civil_no_outliers['BOM_Quant'] <= 0].shape[0])
print(df_rj_materiais_eletricos_no_outliers[df_rj_materiais_eletricos_no_outliers['BOM_Quant'] <= 0].shape[0])

# Verificando se há valores NA
print(df_rj_ferragens_no_outliers['BOM_Quant'].isna().sum())
print(df_rj_construcao_civil_no_outliers['BOM_Quant'].isna().sum())
print(df_rj_materiais_eletricos_no_outliers['BOM_Quant'].isna().sum())

0
0
0
0
0
0

In [26]:
df_rj_ferragens_no_outliers = df_rj_ferragens_no_outliers.reset_index() 
df_rj_ferragens_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True) 

df_rj_construcao_civil_no_outliers = df_rj_construcao_civil_no_outliers.reset_index() 
df_rj_construcao_civil_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True) 

df_rj_materiais_eletricos_no_outliers = df_rj_materiais_eletricos_no_outliers.reset_index() 
df_rj_materiais_eletricos_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True)

In [28]:
df_rj_ferragens_no_outliers.to_csv('../Data/PreparedData/RJ/Semanal/RJ_FERRAGENS.csv', index=False)
df_rj_construcao_civil_no_outliers.to_csv('../Data/PreparedData/RJ/Semanal/RJ_CONSTRUCAO_CIVIL.csv', index=False)
df_rj_materiais_eletricos_no_outliers.to_csv('../Data/PreparedData/RJ/Semanal/RJ_MATERIAIS_ELETRICOS.csv', index=False)

### Criando datasets quinzenais

In [29]:
df_rj_ferragens_quinzenal = df_rj_ferragens_grouped.resample('15D').sum().reset_index()  
df_rj_construcao_civil_quinzenal = df_rj_construcao_civil_grouped.resample('15D').sum().reset_index()  
df_rj_materiais_eletricos_quinzenal = df_rj_materiais_eletricos_grouped.resample('15D').sum().reset_index()

In [30]:
# Substituindo zeros por NaN antes da interpolação  
df_rj_ferragens_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)  
df_rj_construcao_civil_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)  
df_rj_materiais_eletricos_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_35436\854151143.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rj_ferragens_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\854151143.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rj_construcao_civil_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\854151143.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rj_materiais_eletricos_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)

In [31]:
# Preenchendo valores ausentes com interpolação  
df_rj_ferragens_quinzenal['BOM_Quant'] = df_rj_ferragens_quinzenal['BOM_Quant'].interpolate(method='linear')  
df_rj_construcao_civil_quinzenal['BOM_Quant'] = df_rj_construcao_civil_quinzenal['BOM_Quant'].interpolate(method='linear')  
df_rj_materiais_eletricos_quinzenal['BOM_Quant'] = df_rj_materiais_eletricos_quinzenal['BOM_Quant'].interpolate(method='linear')

C:\Users\HP\AppData\Local\Temp\ipykernel_35436\1412374302.py:2: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rj_ferragens_quinzenal['BOM_Quant'] = df_rj_ferragens_quinzenal['BOM_Quant'].interpolate(method='linear')
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\1412374302.py:3: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rj_construcao_civil_quinzenal['BOM_Quant'] = df_rj_construcao_civil_quinzenal['BOM_Quant'].interpolate(method='linear')
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\1412374302.py:4: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rj_materiais_eletricos_quinzenal['BOM_Quant'] = df_rj_materiais_eletricos_quinzenal['BOM_Quant'].interpolate(method='linear')

In [32]:
df_rj_ferragens_no_outliers = remove_outliers(df_rj_ferragens_quinzenal, 'BOM_Quant')  
df_rj_construcao_civil_no_outliers = remove_outliers(df_rj_construcao_civil_quinzenal, 'BOM_Quant')  
df_rj_materiais_eletricos_no_outliers = remove_outliers(df_rj_materiais_eletricos_quinzenal, 'BOM_Quant')

## Verificando se há as series possuem todas as quinzenas

In [33]:
date_range_ferragens = pd.date_range(start=df_rj_ferragens_no_outliers['Proj_Date'].min(),   
                           end=df_rj_ferragens_no_outliers['Proj_Date'].max(),   
                           freq='15D')  
df_rj_ferragens_no_outliers = df_rj_ferragens_no_outliers.set_index('Proj_Date').reindex(date_range_ferragens)

date_range_construcao = pd.date_range(start=df_rj_construcao_civil_no_outliers['Proj_Date'].min(),   
                           end=df_rj_construcao_civil_no_outliers['Proj_Date'].max(),   
                           freq='15D')  
df_rj_construcao_civil_no_outliers = df_rj_construcao_civil_no_outliers.set_index('Proj_Date').reindex(date_range_construcao)

date_range_eletricos = pd.date_range(start=df_rj_materiais_eletricos_no_outliers['Proj_Date'].min(),   
                           end=df_rj_materiais_eletricos_no_outliers['Proj_Date'].max(),   
                           freq='15D')  
df_rj_materiais_eletricos_no_outliers = df_rj_materiais_eletricos_no_outliers.set_index('Proj_Date').reindex(date_range_eletricos)

In [37]:
# Repetido até que todos os valores NA sejam preenchidos
df_rj_ferragens_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rj_ferragens_no_outliers['BOM_Quant'])
df_rj_construcao_civil_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rj_construcao_civil_no_outliers['BOM_Quant']) 
df_rj_materiais_eletricos_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rj_materiais_eletricos_no_outliers['BOM_Quant'])

C:\Users\HP\AppData\Local\Temp\ipykernel_35436\3055885078.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(series[i]):
C:\Users\HP\AppData\Local\Temp\ipykernel_35436\3055885078.py:9: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  result[i] = valid_values.mean()

In [38]:
# Verificando se há valores zero ou negativos
print(df_rj_ferragens_no_outliers[df_rj_ferragens_no_outliers['BOM_Quant'] <= 0].shape[0])
print(df_rj_construcao_civil_no_outliers[df_rj_construcao_civil_no_outliers['BOM_Quant'] <= 0].shape[0])
print(df_rj_materiais_eletricos_no_outliers[df_rj_materiais_eletricos_no_outliers['BOM_Quant'] <= 0].shape[0])

# Verificando se há valores NA
print(df_rj_ferragens_no_outliers['BOM_Quant'].isna().sum())
print(df_rj_construcao_civil_no_outliers['BOM_Quant'].isna().sum())
print(df_rj_materiais_eletricos_no_outliers['BOM_Quant'].isna().sum())

0
0
0
0
0
0

In [39]:
df_rj_ferragens_no_outliers = df_rj_ferragens_no_outliers.reset_index() 
df_rj_ferragens_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True) 

df_rj_construcao_civil_no_outliers = df_rj_construcao_civil_no_outliers.reset_index() 
df_rj_construcao_civil_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True) 

df_rj_materiais_eletricos_no_outliers = df_rj_materiais_eletricos_no_outliers.reset_index() 
df_rj_materiais_eletricos_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True)

In [40]:
df_rj_materiais_eletricos_no_outliers.head()

   Proj_Date BOM_Quant
0 2023-10-03      29.0
1 2023-10-18      24.0
2 2023-11-02      26.5
3 2023-11-17      26.5
4 2023-12-02      24.0

In [41]:
df_rj_ferragens_no_outliers.to_csv('../Data/PreparedData/RJ/Quinzenal/RJ_FERRAGENS.csv', index=False)
df_rj_construcao_civil_no_outliers.to_csv('../Data/PreparedData/RJ/Quinzenal/RJ_CONSTRUCAO_CIVIL.csv', index=False)
df_rj_materiais_eletricos_no_outliers.to_csv('../Data/PreparedData/RJ/Quinzenal/RJ_MATERIAIS_ELETRICOS.csv', index=False)