In [1]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('../Data/products_4.csv')
df.head()

,Prod_Desc,Sub_Name,Cat_Name,ID_Proj,Proj_Name,BOM_Quant,Proj_City,Proj_State,Proj_Date
0,"Gabião tipo caixa, malha hexagonal",Aços para Construção,Construção Civil,10414,Gabião - HEMOBRAS Engeko,34.0,Goiana,PE,2023-09-05
1,"Gabião manta (colchão), malha hexagonal",Aços para Construção,Construção Civil,10414,Gabião - HEMOBRAS Engeko,355.0,Goiana,PE,2023-09-05
2,Vergalhão de aço nervurado,Aços para Construção,Construção Civil,10415,Vergalhão - Prefeitura Municipal de Dois Córregos,136.0,Dois Córregos,SP,2023-09-05
3,CONCRETO USINADO CONVENCIONAL,Concreto,Infraestrutura,10416,CONCRETO USINADO - tejofran,104.0,São Paulo,SP,2023-09-05
4,CAIXA DE CONCRETO ARMADO,Artefatos de Concreto,Infraestrutura,10417,CAIXA DE CONCRETO - JAV,14.0,Lauro de Freitas,BA,2023-09-05

In [2]:
df_rs = df[df['Proj_State'] == 'RS']
df_rs.drop(columns=['Prod_Desc', 'Sub_Name', 'ID_Proj', 'Proj_Name', 'Proj_City'], inplace=True)
df_rs.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_9928\597132560.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rs.drop(columns=['Prod_Desc', 'Sub_Name', 'ID_Proj', 'Proj_Name', 'Proj_City'], inplace=True)

            Cat_Name  BOM_Quant Proj_State   Proj_Date
5   Construção Civil      10.64         RS  2023-09-06
18  Construção Civil      10.00         RS  2023-09-06
36  Construção Civil       1.00         RS  2023-09-19
37  Construção Civil       1.00         RS  2023-09-19
38  Construção Civil       1.00         RS  2023-09-19

In [ ]:
df_rs.isnull().sum()

### Criando um dataset para cada categoria que sera modelada

In [3]:
df_rs_ferragens = df_rs[df_rs['Cat_Name'] == 'Ferragens']
df_rs_construcao_civil = df_rs[df_rs['Cat_Name'] == 'Construção Civil']
df_rs_materiais_eletricos = df_rs[df_rs['Cat_Name'] == 'Materiais Elétricos']

### Agrupamento e Soma de BOM_Quant por Data

In [4]:
df_rs_ferragens_grouped = df_rs_ferragens.groupby('Proj_Date').agg({'BOM_Quant': 'sum'}).reset_index()
df_rs_construcao_civil_grouped = df_rs_construcao_civil.groupby('Proj_Date').agg({'BOM_Quant': 'sum'}).reset_index()
df_rs_materiais_eletricos_grouped = df_rs_materiais_eletricos.groupby('Proj_Date').agg({'BOM_Quant': 'sum'}).reset_index()

In [ ]:
n_duplicates = df_rs_ferragens_grouped.duplicated().sum()
print(f'Número de duplicados: {n_duplicates}')

n_duplicates = df_rs_construcao_civil_grouped.duplicated().sum()
print(f'Número de duplicados: {n_duplicates}')

n_duplicates = df_rs_materiais_eletricos_grouped.duplicated().sum()
print(f'Número de duplicados: {n_duplicates}')

In [5]:
# Verificando se há valores zero ou negativos
print(df_rs_ferragens_grouped[df_rs_ferragens_grouped['BOM_Quant'] <= 0].shape[0])
print(df_rs_construcao_civil_grouped[df_rs_construcao_civil_grouped['BOM_Quant'] <= 0].shape[0])
print(df_rs_materiais_eletricos_grouped[df_rs_materiais_eletricos_grouped['BOM_Quant'] <= 0].shape[0])

0
0
0

In [ ]:
df_rs_ferragens_grouped.to_csv('../Data/PreparedData/RS/RS_FERRAGENS.csv', index=False)
df_rs_construcao_civil_grouped.to_csv('../Data/PreparedData/RS/RS_CONSTRUCAO_CIVIL.csv', index=False)
df_rs_materiais_eletricos_grouped.to_csv('../Data/PreparedData/RS/RS_MATERIAIS_ELETRICOS.csv', index=False)

In [ ]:
plt.figure(figsize=(12, 6))
df_rs.groupby('Proj_Date').size().plot()
plt.title('Products Over Time')
plt.xlabel('Date')
plt.ylabel('Count')
plt.show()

### Criando datasets semanais

In [6]:
def remove_outliers(df, column):  
    Q1 = df[column].quantile(0.25)  
    Q3 = df[column].quantile(0.75)  
    IQR = Q3 - Q1  
    lower_bound = Q1 - 1.5 * IQR  
    upper_bound = Q3 + 1.5 * IQR  
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

In [7]:
df_rs_ferragens_grouped['Proj_Date'] = pd.to_datetime(df_rs_ferragens_grouped['Proj_Date'])  
df_rs_construcao_civil_grouped['Proj_Date'] = pd.to_datetime(df_rs_construcao_civil_grouped['Proj_Date'])  
df_rs_materiais_eletricos_grouped['Proj_Date'] = pd.to_datetime(df_rs_materiais_eletricos_grouped['Proj_Date'])  
  
df_rs_ferragens_grouped.set_index('Proj_Date', inplace=True)  
df_rs_construcao_civil_grouped.set_index('Proj_Date', inplace=True)  
df_rs_materiais_eletricos_grouped.set_index('Proj_Date', inplace=True)

In [8]:
df_rs_ferragens_semanal = df_rs_ferragens_grouped.resample('W').sum().reset_index()  
df_rs_construcao_civil_semanal = df_rs_construcao_civil_grouped.resample('W').sum().reset_index()  
df_rs_materiais_eletricos_semanal = df_rs_materiais_eletricos_grouped.resample('W').sum().reset_index()

In [9]:
# Substituir zeros por NaN antes da interpolação  
df_rs_ferragens_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)  
df_rs_construcao_civil_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)  
df_rs_materiais_eletricos_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_9928\1909988907.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rs_ferragens_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\1909988907.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rs_construcao_civil_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\1909988907.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rs_materiais_eletricos_semanal['BOM_Quant'].replace(0, pd.NA, inplace=True)

In [10]:
df_rs_ferragens_semanal['BOM_Quant'] = df_rs_ferragens_semanal['BOM_Quant'].interpolate(method='linear')  
df_rs_construcao_civil_semanal['BOM_Quant'] = df_rs_construcao_civil_semanal['BOM_Quant'].interpolate(method='linear')  
df_rs_materiais_eletricos_semanal['BOM_Quant'] = df_rs_materiais_eletricos_semanal['BOM_Quant'].interpolate(method='linear')

C:\Users\HP\AppData\Local\Temp\ipykernel_9928\586193128.py:1: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rs_ferragens_semanal['BOM_Quant'] = df_rs_ferragens_semanal['BOM_Quant'].interpolate(method='linear')
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\586193128.py:2: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rs_construcao_civil_semanal['BOM_Quant'] = df_rs_construcao_civil_semanal['BOM_Quant'].interpolate(method='linear')
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\586193128.py:3: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rs_materiais_eletricos_semanal['BOM_Quant'] = df_rs_materiais_eletricos_semanal['BOM_Quant'].interpolate(method='linear')

In [11]:
df_rs_ferragens_no_outliers = remove_outliers(df_rs_ferragens_semanal, 'BOM_Quant')  
df_rs_construcao_civil_no_outliers = remove_outliers(df_rs_construcao_civil_semanal, 'BOM_Quant')  
df_rs_materiais_eletricos_no_outliers = remove_outliers(df_rs_materiais_eletricos_semanal, 'BOM_Quant')

In [12]:
df_rs_ferragens_no_outliers.head()

    Proj_Date BOM_Quant
0  2023-10-15       6.0
4  2023-11-12      10.0
19 2024-02-25       6.0
25 2024-04-07     120.0
30 2024-05-12      20.0

## Verificando se há as series possuem todas as semanas

In [13]:
# Função para calcular a média móvel de 3 valores  
def rolling_mean_imputation(series):  
    result = series.copy()  
    for i in range(len(series)):  
        if pd.isna(series[i]):  
            window = series[max(i-3, 0):i]  
            valid_values = window[~pd.isna(window)]  
            if len(valid_values) > 0:  
                result[i] = valid_values.mean()  
    return result

In [14]:
df_rs_ferragens_no_outliers['Proj_Date'] = pd.to_datetime(df_rs_ferragens_no_outliers['Proj_Date'])  
df_rs_construcao_civil_no_outliers['Proj_Date'] = pd.to_datetime(df_rs_construcao_civil_no_outliers['Proj_Date'])  
df_rs_materiais_eletricos_no_outliers['Proj_Date'] = pd.to_datetime(df_rs_materiais_eletricos_no_outliers['Proj_Date'])  

df_rs_ferragens_no_outliers.set_index('Proj_Date', inplace=True) 
df_rs_construcao_civil_no_outliers.set_index('Proj_Date', inplace=True) 
df_rs_materiais_eletricos_no_outliers.set_index('Proj_Date', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_9928\1057884267.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rs_ferragens_no_outliers['Proj_Date'] = pd.to_datetime(df_rs_ferragens_no_outliers['Proj_Date'])
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\1057884267.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rs_construcao_civil_no_outliers['Proj_Date'] = pd.to_datetime(df_rs_construcao_civil_no_outliers['Proj_Date'])
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\1057884267.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_rs_materiais_eletricos_no_outliers['Proj_Date'] = pd.to_datetime(df_rs_materiais_eletricos_no_outliers['Proj_Date'])

In [15]:
df_rs_materiais_eletricos_no_outliers.head()

           BOM_Quant
Proj_Date
2023-10-08      21.0
2023-10-15       8.0
2023-11-05      84.0
2024-01-21       6.0
2024-03-17       4.0

In [16]:
# Criar um índice de datas completo com frequência semanal  
full_index_ferragens = pd.date_range(start=df_rs_ferragens_no_outliers.index.min(), end=df_rs_ferragens_no_outliers.index.max(), freq='W')
df_rs_ferragens_no_outliers = df_rs_ferragens_no_outliers.reindex(full_index_ferragens)

full_index_construcao = pd.date_range(start=df_rs_construcao_civil_no_outliers.index.min(), end=df_rs_construcao_civil_no_outliers.index.max(), freq='W')
df_rs_construcao_civil_no_outliers = df_rs_construcao_civil_no_outliers.reindex(full_index_construcao)

full_index_eletrico = pd.date_range(start=df_rs_materiais_eletricos_no_outliers.index.min(), end=df_rs_materiais_eletricos_no_outliers.index.max(), freq='W')
df_rs_materiais_eletricos_no_outliers = df_rs_materiais_eletricos_no_outliers.reindex(full_index_eletrico)

In [26]:
# Repetido até que todos os valores NA sejam preenchidos
df_rs_ferragens_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rs_ferragens_no_outliers['BOM_Quant'])
df_rs_construcao_civil_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rs_construcao_civil_no_outliers['BOM_Quant']) 
df_rs_materiais_eletricos_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rs_materiais_eletricos_no_outliers['BOM_Quant'])

C:\Users\HP\AppData\Local\Temp\ipykernel_9928\3055885078.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(series[i]):
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\3055885078.py:9: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  result[i] = valid_values.mean()

In [27]:
# Verificando se há valores zero ou negativos
print(df_rs_ferragens_no_outliers[df_rs_ferragens_no_outliers['BOM_Quant'] <= 0].shape[0])
print(df_rs_construcao_civil_no_outliers[df_rs_construcao_civil_no_outliers['BOM_Quant'] <= 0].shape[0])
print(df_rs_materiais_eletricos_no_outliers[df_rs_materiais_eletricos_no_outliers['BOM_Quant'] <= 0].shape[0])

# Verificando se há valores NA
print(df_rs_ferragens_no_outliers['BOM_Quant'].isna().sum())
print(df_rs_construcao_civil_no_outliers['BOM_Quant'].isna().sum())
print(df_rs_materiais_eletricos_no_outliers['BOM_Quant'].isna().sum())

0
0
0
0
0
0

In [28]:
df_rs_ferragens_no_outliers = df_rs_ferragens_no_outliers.reset_index() 
df_rs_ferragens_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True) 

df_rs_construcao_civil_no_outliers = df_rs_construcao_civil_no_outliers.reset_index() 
df_rs_construcao_civil_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True) 

df_rs_materiais_eletricos_no_outliers = df_rs_materiais_eletricos_no_outliers.reset_index() 
df_rs_materiais_eletricos_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True)

In [31]:
df_rs_ferragens_no_outliers.to_csv('../Data/PreparedData/RS/Semanal/RS_FERRAGENS.csv', index=False)
df_rs_construcao_civil_no_outliers.to_csv('../Data/PreparedData/RS/Semanal/RS_CONSTRUCAO_CIVIL.csv', index=False)
df_rs_materiais_eletricos_no_outliers.to_csv('../Data/PreparedData/RS/Semanal/RS_MATERIAIS_ELETRICOS.csv', index=False)

### Criando datasets quinzenais

In [32]:
df_rs_ferragens_quinzenal = df_rs_ferragens_grouped.resample('15D').sum().reset_index()  
df_rs_construcao_civil_quinzenal = df_rs_construcao_civil_grouped.resample('15D').sum().reset_index()  
df_rs_materiais_eletricos_quinzenal = df_rs_materiais_eletricos_grouped.resample('15D').sum().reset_index()

In [33]:
df_rs_ferragens_quinzenal.head()

   Proj_Date  BOM_Quant
0 2023-10-09        6.0
1 2023-10-24      460.0
2 2023-11-08        0.0
3 2023-11-23        0.0
4 2023-12-08        0.0

In [34]:
# Substituindo zeros por NaN antes da interpolação  
df_rs_ferragens_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)  
df_rs_construcao_civil_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)  
df_rs_materiais_eletricos_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_9928\2973366355.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rs_ferragens_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\2973366355.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rs_construcao_civil_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\2973366355.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_rs_materiais_eletricos_quinzenal['BOM_Quant'].replace(0, pd.NA, inplace=True)

In [35]:
# Preenchendo valores ausentes com interpolação  
df_rs_ferragens_quinzenal['BOM_Quant'] = df_rs_ferragens_quinzenal['BOM_Quant'].interpolate(method='linear')  
df_rs_construcao_civil_quinzenal['BOM_Quant'] = df_rs_construcao_civil_quinzenal['BOM_Quant'].interpolate(method='linear')  
df_rs_materiais_eletricos_quinzenal['BOM_Quant'] = df_rs_materiais_eletricos_quinzenal['BOM_Quant'].interpolate(method='linear')

C:\Users\HP\AppData\Local\Temp\ipykernel_9928\4130470751.py:2: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rs_ferragens_quinzenal['BOM_Quant'] = df_rs_ferragens_quinzenal['BOM_Quant'].interpolate(method='linear')
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\4130470751.py:3: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rs_construcao_civil_quinzenal['BOM_Quant'] = df_rs_construcao_civil_quinzenal['BOM_Quant'].interpolate(method='linear')
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\4130470751.py:4: FutureWarning: Series.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df_rs_materiais_eletricos_quinzenal['BOM_Quant'] = df_rs_materiais_eletricos_quinzenal['BOM_Quant'].interpolate(method='linear')

In [36]:
df_rs_ferragens_no_outliers = remove_outliers(df_rs_ferragens_quinzenal, 'BOM_Quant')  
df_rs_construcao_civil_no_outliers = remove_outliers(df_rs_construcao_civil_quinzenal, 'BOM_Quant')  
df_rs_materiais_eletricos_no_outliers = remove_outliers(df_rs_materiais_eletricos_quinzenal, 'BOM_Quant')

## Verificando se há as series possuem todas as quinzenas

In [37]:
date_range_ferragens = pd.date_range(start=df_rs_ferragens_no_outliers['Proj_Date'].min(),   
                           end=df_rs_ferragens_no_outliers['Proj_Date'].max(),   
                           freq='15D')  
df_rs_ferragens_no_outliers = df_rs_ferragens_no_outliers.set_index('Proj_Date').reindex(date_range_ferragens)

date_range_construcao = pd.date_range(start=df_rs_construcao_civil_no_outliers['Proj_Date'].min(),   
                           end=df_rs_construcao_civil_no_outliers['Proj_Date'].max(),   
                           freq='15D')  
df_rs_construcao_civil_no_outliers = df_rs_construcao_civil_no_outliers.set_index('Proj_Date').reindex(date_range_construcao)

date_range_eletricos = pd.date_range(start=df_rs_materiais_eletricos_no_outliers['Proj_Date'].min(),   
                           end=df_rs_materiais_eletricos_no_outliers['Proj_Date'].max(),   
                           freq='15D')  
df_rs_materiais_eletricos_no_outliers = df_rs_materiais_eletricos_no_outliers.set_index('Proj_Date').reindex(date_range_eletricos)

In [41]:
# Repetido até que todos os valores NA sejam preenchidos
df_rs_ferragens_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rs_ferragens_no_outliers['BOM_Quant'])
df_rs_construcao_civil_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rs_construcao_civil_no_outliers['BOM_Quant']) 
df_rs_materiais_eletricos_no_outliers['BOM_Quant'] = rolling_mean_imputation(df_rs_materiais_eletricos_no_outliers['BOM_Quant'])

C:\Users\HP\AppData\Local\Temp\ipykernel_9928\3055885078.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if pd.isna(series[i]):
C:\Users\HP\AppData\Local\Temp\ipykernel_9928\3055885078.py:9: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  result[i] = valid_values.mean()

In [42]:
# Verificando se há valores zero ou negativos
print(df_rs_ferragens_no_outliers[df_rs_ferragens_no_outliers['BOM_Quant'] <= 0].shape[0])
print(df_rs_construcao_civil_no_outliers[df_rs_construcao_civil_no_outliers['BOM_Quant'] <= 0].shape[0])
print(df_rs_materiais_eletricos_no_outliers[df_rs_materiais_eletricos_no_outliers['BOM_Quant'] <= 0].shape[0])

# Verificando se há valores NA
print(df_rs_ferragens_no_outliers['BOM_Quant'].isna().sum())
print(df_rs_construcao_civil_no_outliers['BOM_Quant'].isna().sum())
print(df_rs_materiais_eletricos_no_outliers['BOM_Quant'].isna().sum())

0
0
0
0
0
0

In [44]:
df_rs_ferragens_no_outliers = df_rs_ferragens_no_outliers.reset_index() 
df_rs_ferragens_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True) 

df_rs_construcao_civil_no_outliers = df_rs_construcao_civil_no_outliers.reset_index() 
df_rs_construcao_civil_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True) 

df_rs_materiais_eletricos_no_outliers = df_rs_materiais_eletricos_no_outliers.reset_index() 
df_rs_materiais_eletricos_no_outliers.rename(columns={'index': 'Proj_Date'}, inplace=True)

In [46]:
df_rs_ferragens_no_outliers.to_csv('../Data/PreparedData/RS/Quinzenal/RS_FERRAGENS.csv', index=False)
df_rs_construcao_civil_no_outliers.to_csv('../Data/PreparedData/RS/Quinzenal/RS_CONSTRUCAO_CIVIL.csv', index=False)
df_rs_materiais_eletricos_no_outliers.to_csv('../Data/PreparedData/RS/Quinzenal/RS_MATERIAIS_ELETRICOS.csv', index=False)